name: autodesigner_ui
channels:
  - conda-forge
dependencies:
  - pip:
      - biopython==1.79
      - deepspeed==0.5.3
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.2
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - torch==1.10.0
      - tqdm==4.62.2
      - typing-extensions==3.10.0.2
      - pytorch_lightning==1.5.0
      - git+git://github.com/NVIDIA/dllogger.git
      - nvidia-pyindex
      - nvidia-dllogger
  - conda-forge::python=3.7
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - bioconda::aria2
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
